# Generated by Django 4.2.2 on 2023-06-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stud_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stud_name',
        ),
        migrations.AddField(
            model_name='student',
            name='student_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_gender',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
